defaults:
  - _self_

bc_dataset:
  _target_: read_data.custom.BCDataset 
  path: "/home_shared/grail_sissi/vr-hand-tracking/Franka-Teach/proc_data"
  suite: ${suite.name}                  # references custom suite
  num_demos_per_task: ${num_demos_per_task}
  obs_type: ${obs_type}
  history: ${suite.history}
  history_len: ${suite.history_len}
  prompt: ${prompt}
  scenes: ["default_scene"]
  tasks: ["demo_task"]
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}
  img_size: 128
  store_actions: true
