defaults:
  - _self_

name: "custom"

# Training-related parameters
frame_stack: 1
action_repeat: 1
discount: 0.99
hidden_dim: 256

# Data + history
history: false
history_len: 1

# Evaluation settings
eval: false
num_eval_episodes: 1
eval_history_len: 1

# Observation keys
pixel_keys: ["pixels"]
proprio_key: "proprioceptive"
feature_key: "features"

# Snapshot saving
save_snapshot: true

# === Entry point for your teleop dataset ===
_target_: custom_suite.make
demo_folder: ${hydra:runtime.cwd}/proc_data
obs_type: pixels
history_len: ${suite.history_len}
eval: ${suite.eval}
