_target_: suite.custom.CustomSuite
dataset: ${dataloader}
env_cls: flexible_custom_suite.DummyEnv
hidden_dim: 256
name: custom

history: false
history_len: 1
eval_history_len: 1

pixel_keys: ["pixels0"]               
proprio_key: "features"   
feature_key: "features"     
action_repeat: 1              
num_eval_episodes: 1
discount: 0.99

num_train_steps:  5000 #600000 
log_every_steps: 1000
save_every_steps: 2500 #200000
eval_every_steps: 5000 # 200000  

task_make_fn:
  _target_: suite.custom.task_make_fn
  dataset: ${dataloader}
  max_episode_len: 1000
  max_state_dim: 50
  max_action_dim: 10
