_target_: suite.custom.CustomSuite
dataset: ${dataloader}
env_cls: flexible_custom_suite.DummyEnv
hidden_dim: 256
name: custom

history: false
history_len: 1
eval_history_len: 1

pixel_keys: ["pixels0"]               
proprio_key: "features"   
feature_key: "features"     
action_repeat: 1              
num_eval_episodes: 1
discount: 0.99

task_make_fn:
  _target_: suite.custom.task_make_fn
  dataset: ${dataloader}
  env_cls: suite.custom.DummyEnv   # <--- add this
  max_episode_len: 1000
  max_state_dim: 50
  max_action_dim: 10
